---
name: ylib
version: 0.002
author:
  - 'David Golden <dagolden@cpan.org>'
abstract: Add paths to @INC from a config file
license: apache
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=ylib
  repository: http://github.com/dagolden/ylib/
requires:
  File::HomeDir: 0.86
  Path::Class: 0.16
  perl: 5.006
build_requires:
  File::Basename: 0
  File::Copy: 2.11
  File::pushd: 1
  Test::More: 0.62
provides:
  ylib:
    file: lib/ylib.pm
    version: 0.002
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
